### ISSUE TITLE
Issue with requiring Ruby 2.7

### ISSUE THREAD

**Issue by ronaldtse** [fontist/excavate#22]
As implemented in #30, I have some concern with requiring Ruby 2.7 because macOS Big Sur comes default with Ruby 2.6. If we can remain compliant with Ruby 2.6 without change, then we should stay that way. If not, upgrading to requiring 2.7 is okay.

**Comment by maxirmx** [comment]
This issue is applicable to ffi-libarchive-binary and pngcheck-ruby
I will do a quick test

**Comment by maxirmx** [comment]
Now I recall

Since we now have some gems prepackage for linux-musl  general requirement for metanorma package is bundler >= 2.3.22
If this version of bundler is installed atop of Ruby 2.6 an issue arise for metanorma gemfiles:
```
  Bundler could not find compatible versions for gem "isodoc":
    In Gemfile:
      metanorma was resolved to 1.5.1, which depends on
        isodoc (>= 2.3.1)
  
      metanorma-iso was resolved to 1.4.3.pre.alpha, which depends on
        isodoc (~> 1.1.3.pre.alpha3)
```

**Comment by ronaldtse** [comment]
@maxirmx if that's the case why don't we just enforce Ruby 2.7 throughout, if linux-musl is the issue.

**Comment by ronaldtse** [comment]
See this for Metanorma min Ruby at 2.7: https://github.com/metanorma/metanorma/issues/264

**Comment by ronaldtse** [comment]
Let's just go with 2.7 as the minimum Ruby version.
